version: '3'
services:
  redis:
    container_name: redis
    image: redis:6.2.5
    ports:
      - '6379:6379'
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
